
development:
  adapter: postgresql
  database: appearhere_development
  encoding: unicode
  username: 
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: appearhere_test
  encoding: unicode  
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: appearhere_production
  encoding: unicode
  pool: 5
  timeout: 5000
